---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: app
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
#        consul.hashicorp.com/transparent-proxy: "false"
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: "{{ .Values.backend_image.name }}:{{ .Values.backend_image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: "PG_HOST"
              value: {{ .Values.postgres.db_host }}
            - name: "PG_PORT"
              value: {{ .Values.postgres.port | quote }}
            - name: "PG_DB_NAME"
              value: {{ .Values.postgres.db_name }}
            - name: "PG_USER"
              value: {{ .Values.postgres.db_user }}
            - name: "PG_PASS"
              value: "schedule"
            - name: "REDIS_HOST"
              value: "localhost"
            - name: "REDIS_PORT"
              value: "6379"
            - name: "MONGO_HOST"
              value: "localhost"
            - name: "MONGO_PORT"
              value: "27017"
            - name: "MONGO_DB_NAME"
              value: "schedules"

        - name: redis
          image: "redis:7-alpine"
          ports:
            - containerPort: 6379

        - name: postgres
          image: "postgres:14-alpine"
          ports:
            - containerPort: 5432
          env:
             - name: "POSTGRES_DB"
               value: "schedule"
             - name: "POSTGRES_USER"
               value: "schedule"
             - name: "POSTGRES_PASSWORD"
               value: "schedule"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: backend # will be in serv.consul
  namespace: app
spec:
  protocol: "http"
