---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: app

spec:
  destination:
    name: backend
  sources:
    - name: frontend
      action: allow
