# Default values for app_chart Backend.

appName: class-schedule
serviceName: backend-service
namespace: app
replicasCount: 1
backend_image:
  name: stratiiv/devops-team-green
  tag: v1
postgres:
  db_host: "localhost"
  port: 5432
  db_name: "schedule"
  db_user: "schedule"
mongodb:
  host: "localhost"
  port: 27017
  db_name: "schedules"
redis:
  host: "localhost"
  port: 6379