apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      serviceAccountName: frontend
      imagePullSecrets:
        - name: nexus-token
      containers:
        - name: frontend
          image: "{{ .Values.frontend_image.name }}:{{ .Values.frontend_image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http