---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
  labels:
    app: front
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: front
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: front
  namespace: app
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: app
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      service: front
      app: front
  template:
    metadata:
      labels:
        service: front
        app: front
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: front
      containers:
      - name: front
#        image: stratiiv/schedule-frontend:latest
        image: stratiiv/schedule-frontend:test-5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            name: http
        env:
          - name: "API_URL"
            value: "localhost"
          - name: "API_PORT"
            value: "8080"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: front # will be in serv.consul
  namespace: app
spec:
  protocol: "http"
