# This functionality is in beta and is subject to change. The code is provided as-is with no warranties.
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: app
# Allow traffic from nginx to frontend
spec:
  destination:
    name: frontend-service
  sources:
    - name: backend-service
      action: allow
    - name: nginx-service
      action: deny


