---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.deployment.replicasCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: "{{ .Values.backend_image.name }}:{{ .Values.backend_image.tag }}"
          imagePullPolicy: {{ .Values.backend_image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: "PG_HOST"
              value: {{ .Values.postgres.db_host }}
            - name: "PG_PORT"
              value: {{ .Values.postgres.port | quote }}
            - name: "PG_DB_NAME"
              value: {{ .Values.postgres.db_name }}
            - name: "PG_USER"
              value: {{ .Values.postgres.db_user }}
            - name: "PG_PASS"
              value: {{ .Values.postgres.db_password }}
            - name: "REDIS_HOST"
              value: {{ .Values.redis.host }}
            - name: "REDIS_PORT"
              value: {{ .Values.redis.port }}
            - name: "MONGO_HOST"
              value: {{ .Values.mongodb.host }}
            - name: "MONGO_PORT"
              value: {{ .Values.mongodb.port }}
            - name: "MONGO_DB_NAME"
              value: {{ .Values.mongodb.db_name }}

        - name: redis
          image: "redis:7-alpine"
          ports:
            - containerPort: 6379
