# Default values for backend.
appName: class-schedule
serviceName: backend
service:
  type: ClusterIP
  port: 8080

namespace: consul
deployment:
  replicasCount: 2

backend_image:
  name: stratiiv/devops-team-green
  tag: v1
  pullPolicy: IfNotPresent

postgres:
  db_host: "localhost"
  port: 5432
  db_name: "schedule"
  db_user: "schedule"
  db_password: ""
mongodb:
  host: "localhost"
  port: 27017
  db_name: "schedules"
redis:
  host: "localhost"
  port: 6379
  db_name: "mongo"
